### ISSUE TITLE
Issues downloading CUB_200 dataset

### ISSUE THREAD

**Issue by rvinas** [snap-stanford/comet#1]
Congratulations on the nice work!

I'm having some issues downloading the CUB 200 dataset with the `download_CUB.sh` script. It seems that the `wget` command does not work for Google Drive folders. Instead, the following command seems to work:

`gdown https://drive.google.com/uc?id=1hbzc_P1FuxMkcabkgn9ZKinBwW683j45`

**Comment by mbrbic** [comment]
Thanks a lot Ramon! We updated `download_CUB.sh` script.
